### ISSUE TITLE
RestApiCloudWatchRole is not cleaned up with aws-cdk >= 2.38.0

### ISSUE THREAD

**Issue by luismeyer** [clebert/aws-simple#169]
Since Version [2.38.0](https://github.com/aws/aws-cdk/releases/tag/v2.38.0) AWS cdk adds the RemovalPolicy "Retain" to the [CloudwatchRole](https://github.com/aws/aws-cdk/blob/78c858f26fe9b688dc0260d7e8a59004b57c388d/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L535) which is created automatically for RestApi's. This results in the CloudWatchRole leaking after the Stack was deleted. Therefor more and more IAM Roles are added in our AWS.

The [issue](https://github.com/aws/aws-cdk/issues/10878) was that the RestAPI CloudWatchRole was overwriting the  AccountLevel Role for RestAPI's.

Reading from the [ApiGateway Doc's](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway-readme.html#deployments), i think aws-simple shouldn't create a new Log Role for every Stack
`Note: there can only be a single apigateway.CfnAccount per AWS environment so if you create multiple RestApis with cloudWatchRole=true each new RestApi will overwrite the CfnAccount. It is recommended to set cloudWatchRole=false (the default behavior if @aws-cdk/aws-apigateway:disableCloudWatchRole is enabled) and only create a single CloudWatch role and account per environment.`

A solution would be enabling the FeatureFlag @aws-cdk/aws-apigateway:disableCloudWatchRole to prevent the creation of the CloudWatch role by default.

```
new App({
    context: {
        '@aws-cdk/aws-apigateway:disableCloudWatchRole': true,
    },
})
```

**Comment by clebert** [comment]
Hello Luis,

Thank you for your detailed description of the issue. We have decided to keep the current behavior. But to address the issue there is now a new helper command `aws-simple cleanup` to delete REST-API CloudWatch roles that are no longer associated with a stack.

I hope this works for you.

Please see => https://github.com/clebert/aws-simple/commit/7c433798301000e42eebac3015005faf59b74c6e
