### ISSUE TITLE
Can not clean up without having lambda/s3 artifacts built

### ISSUE THREAD

**Issue by unstubbable** [clebert/aws-simple#20]
When `require.resolve` is used in the `aws-simple` config file to define the `localPath`s for the lambda and s3 integrations, the `clean-up` command can not be executed unless the lambda/s3 code has been built before.

Quickly looking through the code, it seems that the local paths are not needed for the clean-up command. Therefore I propose to lazily evaluate them for the other commands where they are needed, e.g. by changing `localPath: string` to `getLocalPath: () => string`.

**Comment by clebert** [comment]
The latest release provides a solution to the problem:
https://github.com/clebert/aws-simple/releases/tag/v0.0.20

An excerpt from the README:

The `AppConfigCreator` function optionally gets a `port` argument. It is set when the function is called from the local DEV server. This gives the opportunity to create different [`AppConfig` objects](https://github.com/clebert/aws-simple/blob/master/src/types.ts#L59) for AWS or the local DEV environment.

**Comment by clebert** [comment]
There is a solution for this problem with the latest release:
https://github.com/clebert/aws-simple/releases/tag/v0.0.21

An excerpt from the README:

The createStackConfig function optionally gets a port argument. It is set when the function is called in the context of the local DEV server. This gives the opportunity to create different StackConfig objects for either AWS or the local DEV environment.
