### ISSUE TITLE
Dev server to handle POST data

### ISSUE THREAD

**Issue by martins-giberts** [clebert/aws-simple#54]
Dev server could be enhanced to support POST data for `docker-lambda`.

**Comment by clebert** [comment]
We implemented the functionality on 6 December. Are you using the latest version?

https://github.com/clebert/aws-simple/issues/45

**Comment by martins-giberts** [comment]
I am using currently latest `v.0.0.36`. I will refine my example code and see if I have made any error. It looks like it should work already.

**Comment by martins-giberts** [comment]
Tried with clean setup, works as expected.
